### ISSUE TITLE
Cursor colour enhancement?

### ISSUE THREAD

**Issue by brihadeesh** [Justintime50/github-dark-vscode-emacs-theme#2]
I've been using this theme for over a month now and it's great except that the cursor can appear too well camouflaged on the dark background. Perhaps setting it to a brighter colour might be called for? I've manually set it to white (#ffffff) for now.

Happy to share screenshots of this if necessary.

**Comment by Justintime50** [comment]
Thanks for reporting this! I use Emacs inside iTerm 2 which by default set my cursor to white so I never noticed this issue. I was able to reproduce the dark gray cursor when opening Emacs directly in a window. I've released `v0.3.1` that changes the cursor to white from gray. Melpa could take upwards of ~24 hours to rebuild the package and pull in this update.

I'd suggest updating this theme tomorrow and you should see the corrected cursor then.
